version: '3'
services:
  web:
    image: roundcube/roundcubemail
    ports:
      - "8052:80"
    environment:
      TZ: 'America/Argentina/Buenos_Aires'
      ROUNDCUBEMAIL_DEFAULT_HOST: ssl://outlook.office365.com
      ROUNDCUBEMAIL_DEFAULT_PORT: 993
      ROUNDCUBEMAIL_SMTP_SERVER: ssl://outlook.office365.com
      ROUNDCUBEMAIL_SMTP_PORT: 587
      ROUNDCUBEMAIL_UPLOAD_MAX_FILESIZE: 50M
      ROUNDCUBEMAIL_DB_TYPE: mysql
      ROUNDCUBEMAIL_DB_HOST: db
      ROUNDCUBEMAIL_DB_PORT: 3306
      ROUNDCUBEMAIL_DB_USER: roundcube
      ROUNDCUBEMAIL_DB_PASSWORD: roundcube
      ROUNDCUBEMAIL_DB_NAME: roundcube
    depends_on:
      - db
    volumes:
      - /mnt/DEPOSITO_2018/:/storage
  db:
    image: mysql/mysql-server:5.7
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - ./mysqldata:/var/lib/mysql
    environment:
      MYSQL_USER: roundcube
      MYSQL_PASSWORD: roundcube
      MYSQL_DATABASE: roundcube
      MYSQL_ROOT_PASSWORD: roundcuber
      TZ: 'America/Argentina/Buenos_Aires'

