version: "2.1"
services:
  transmission:
    image: linuxserver/transmission
    container_name: transmission
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - TRANSMISSION_WEB_HOME=/combustion-release/ #optional
      - USER=username #optional
      - PASS=password #optional
    volumes:
      - ../../docker-data/16-Transmission/config:/config
      - ../../docker-data/16-Transmission/Downloads:/downloads
      - ../../docker-data/16-Transmission/watch:/watch
    ports:
      - 8066:9091
      - 51413:51413
      - 51413:51413/udp
    restart: unless-stopped
