version: "3"
services:
    jellyfin:
      image: jellyfin/jellyfin:latest
      volumes:
        - ../../docker-data/05-jellyfin/config:/config
        - ../../docker-data/05-jellyfin/cache:/cache
        - ../../docker-data/05-jellyfin/Video:/media/video
        - ../../docker-data/05-jellyfin/Musica:/media/musica
      restart: always
      ports:
      - 8055:8096
