version: '3'
services:
  homeassistant:
    container_name: home-assistant
    image: homeassistant/home-assistant:stable
    volumes:
      - ../../docker-data/12-homeassistant/config:/config
    environment:
      - TZ=America/Argentina/Buenos_Aires
    restart: always
    network_mode: host
