version: '3.3'
services:
  home-assistant:
    image: homeassistant/home-assistant:stable
    volumes:
      - ../../docker-data/12-homeassistant/config:/config
      - /etc/localtime:/etc/localtime:ro
    restart: always
    network_mode: "host"

