version: "2.1"
services:
  jackett:
    image: linuxserver/jackett
    container_name: jackett
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - AUTO_UPDATE=true #optional
      - RUN_OPTS=run options here #optional
    volumes:
      - ../../docker-data/11-jacket/config:/config
      - ../../docker-data/11-jacket/dowloads:/downloads
    ports:
      - 8061:9117
    restart: unless-stopped
